// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfIpwOTkLFbrRQCdxdlK2dS39Bn3kj0lY',
    appId: '1:112345167578:web:cafdf6bc55932750b257e3',
    messagingSenderId: '112345167578',
    projectId: 'uni-junction',
    authDomain: 'uni-junction.firebaseapp.com',
    storageBucket: 'uni-junction.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKgIJFDD0PfgChbJMxVdgP_MGVGXKTI30',
    appId: '1:112345167578:android:2afe65e2b8d1ce61b257e3',
    messagingSenderId: '112345167578',
    projectId: 'uni-junction',
    storageBucket: 'uni-junction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB21bQMlI7HX1I0JpCwK3Zz2ouCnX_g67w',
    appId: '1:112345167578:ios:5a8ff5e2da7849e5b257e3',
    messagingSenderId: '112345167578',
    projectId: 'uni-junction',
    storageBucket: 'uni-junction.appspot.com',
    iosBundleId: 'com.example.uniJunction',
  );
}
